feat(01-building-blocks): comment fail step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -16,10 +16,9 @@ jobs:
         run: |
           echo "I will succeed"
           echo 0
-      
-      - name: Fail step
-        run: |
-            echo "I will fail"
-            exit 1
+      # - name: Fail step
+      #   run: |
+      #       echo "I will fail"
+      #       exit 1
       - name: Say goodbye
         run: echo "Goodbye!"
